language: r
  
r:
  - oldrel
  - release
  - devel

matrix:
  allow_failures:
    - r: 3.5
    
repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

warnings_are_errors: false


