language: r

r:
 - 3.2
 - 3.3
 - 3.4
 - oldrel
 - release
 - devel
 
matrix:
  allow_failures:
    - r: 3.4
    
r_github_packages: quicklizard99/cheddar

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org
  
warnings_are_errors: false
r_build_args: "--no-manual"
r_check_args: "--no-manual --as-cran"
