language: r

r:
  - oldrel
  - release
  - devel
  
TRAVIS_R_VERSION_STRING: 3.6.1

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

matrix:
  include:
  - os: linux
    r: release
    addons:
        apt:
            packages:
                - r-cran-rgtk2
  - os: linux
    r: oldrel
    addons:
        apt:
            packages:
                - r-cran-rgtk2
  - os: linux
    r: devel
    addons:
        apt:
            packages:
                - r-cran-rgtk2

warnings_are_errors: true
r_build_args: "--no-manual"
r_check_args: "--no-manual --as-cran"

