language: r

install:
  - R CMD INSTALL .
  - R -e 'remotes::install_deps(dependencies = TRUE)'
  
r:
 - 3.4
 - 3.5
 - 3.6
 - devel

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

warnings_are_errors: false


