language: r

sudo: required
  
r:
 - 3.4
 - 3.5
 - 3.6
 - oldrel
 - release
 - devel
 
 apt_packages:
    - libgdal-dev
    - libproj-dev
    - libcairo2-dev
    - libatk1.0-dev
    - libpango1.0-dev
    - libgtk2.0-dev
    - libglib2.0-dev
    - libcurl4-openssl-dev
    - libudunits2-dev
    
r_binary_packages:
    - cairoDevice
    - RGtk2
    
r_github_packages: 
  - quicklizard99/cheddar
    
repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org
  
warnings_are_errors: false
r_build_args: "--no-manual"
r_check_args: "--no-manual --as-cran"
