language: r

r:
  - oldrel
  - release

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

warnings_are_errors: true
r_build_args: "--no-manual"
r_check_args: "--no-manual --as-cran"

